massalabs/ui-kit

- src/global.css
We are adding an **default-input** class under the global styles.
It will allow us to DRY in terms of styles for all input fields.
⚠️ _an open question remains concerning the @apply_
> add default input class in globals

- src/components/AccountSelector/AccountSelectButton/AccountSelector.stories.tsx
- src/components/AccountSelector/AccountSelectButton/AccountSelector.test.tsx
- src/components/AccountSelector/AccountSelectButton/AccountSelectorButton.tsx
- src/components/AccountSelector/AccountSelectButton/index.ts
- src/components/AccountSelector/index.ts
- src/components/index.ts
This is a cleaner branch than [32-add-account-selector](https://github.com/massalabs/Ui-Kit/tree/32-add-account-selector) ! Once merged I will delete previous.
> add selector

- src/components/index.ts
The index export show an error. We remove it because there is no Icon or SVG component to export.
> remove index export

- src/components/Button/Button.tsx
Quick fix for the text displacement of the button. The issue was that : 
- the leading normal was setting line height to 1px on buttons and over-riding the line-height : 20px set in the presets. 
Here we can see the text is not centered : 
Removing leading normal should fix and recenter
> remove leading normal to fix displacement

- src/components/Stepper/Stepper.stories.tsx
- src/components/Stepper/Stepper.test.tsx
- src/components/Stepper/Stepper.tsx
- src/components/Stepper/index.ts
We are adding the `<Stepper>` component.
⚠️ We are not following the exact design for that, for now.
> add stepper component

- src/components/Input/Input.tsx
We don't need placeholder since is a native prop and we take with ...rest props
> remove placeholder

- src/components/Password/Password.stories.tsx
- src/components/Password/Password.test.tsx
- src/components/Password/Password.tsx
We are adding the error/warning API for `<Password>` component.
> add error under password field

- src/components/SideMenu/SideMenu.stories.tsx
- src/components/SideMenu/SideMenu.test.tsx
- src/components/SideMenu/SideMenu.tsx
- src/components/SideMenu/index.ts
- src/components/index.ts
We are adding a `<SideMenu>` component.
⚠️  We must fix SVG + JEST to be able to test.
> add side-menu

- src/components/PopupModal/PopupModal.tsx
We are fixing the close button color on modal
|before|after|
|-|-|
|<img width="151" alt="Screenshot 2023-05-25 at 10 42 48" src="https://github.com/massalabs/ui-kit/assets/126461030/32ac83da-1d02-4f49-9de1-15ff991b47b1">|<img width="171" alt="Screenshot 2023-05-25 at 10 42 07" src="https://github.com/massalabs/ui-kit/assets/126461030/e3be0d4c-6f45-4cb2-96bd-0c335cbfd825">|
> fix modal close button color

- src/components/AccountSelector/AccountSelector.stories.tsx
- src/components/AccountSelector/AccountSelector.tsx
We are fixing some account selector colors
> fix account selector

- src/components/Input/Input.stories.tsx
We are adding some input variants under storybook
> add input variants

- src/components/SideMenu/SideMenu.tsx
We are fixing trick typo on side menu.
TO
> fix side menu typo items

- babel.config.cjs
When we run tests with jest when files have "usestate<T>" (eg: usestate<string>)  we need this config.
> add typescript

- src/components/RadioButton/RadioButton.stories.tsx
- src/components/RadioButton/RadioButton.test.tsx
- src/components/RadioButton/RadioButton.tsx
- src/components/RadioButton/index.ts
- src/components/index.ts
> add RadioButton

- src/components/Icons/Svg/Massa/MassaWallet.tsx
We missed a rounded in wallet massa logo. This MR fixed that.
> missing round lg on massa wallet logo

- src/components/Plugin/Plugin.stories.tsx
we changed the icon color prop to use tailwind preset s-warning
before : 
after  :
> change icon color prop

- src/components/LayoutStation/LayoutStation.tsx
We add correct padding to layout component :
80px on x axis,
48 on top 
32 on bot
Before : 
After :
> Add Correct Padding to Layout

- src/components/LayoutStation/LayoutStation.tsx
We are removing `h-screen` for layout.
Check below :
BEFORE
AFTER
> remove height value

- src/components/LayoutStation/LayoutStation.tsx
There was a change on the layout height that introduced unexpected behavior. This pr is a correction so set min h-screen and not block the scroll. It is so we don't have to set the h-screen in children component see example : 
no h-screen in component 
with min-h-screen :
> Add min-h to Layout

- src/components/Plugin/Plugin.tsx
We try to fix an error that appears when using the component 
`Type '{ preIcon: Element; topAction: Element; title: string; subtitle: string; subtitleIcon: Element; content: (false | Element)[]; } | { preIcon: Element; ... 4 more ...; content: Element[]; }' is not assignable to type 'IntrinsicAttributes & PluginProps'.
Type '{ preIcon: Element; topAction: Element; title: string; subtitle: string; subtitleIcon: Element | null; content: Element[]; }' is not assignable to type 'PluginProps'.
Types of property 'subtitleIcon' are incompatible.
Type 'Element | null' is not assignable to type 'Element | undefined'.
Type 'null' is not assignable to type 'Element | undefined'.` 
because we add a conditional in our subtitleIcon to render or not the the certificate icon :
`subtitleIcon: author === …
> Add null to subtitleIcon

- src/components/Icons/Svg/Massa/Certificate.tsx
We add camelCase to fix error 
`act-dom.development.js:86 Warning: Invalid DOM property `stroke-linejoin`. Did you mean `strokeLinejoin`?
at path
at svg
at Certificate (http://localhost:5173/node_modules/.vite/deps/@massalabs_react-ui-kit.js?t=1686752369481&v=9a032a34:799:9)
`
> Add Camel Case to SVG

- src/components/Icons/Svg/Massa/StationLogo.tsx
- src/components/Icons/Svg/SvgIcon.stories.tsx
- src/components/LayoutStation/LayoutStation.tsx
- src/components/ThemeMode/ThemeMode.tsx
We are updating theme component.
> Update theme component

- src/components/DashboardStation/DashboardStation.tsx
- src/components/PluginWallet/PluginWallet.tsx
- Have images take up all the space
- Let's reduce the size font of the title if possible because I don't it nice to see Massa Wallet written like this.... wdyt?
Expected: it should be in only 1 line I would say
> for for dashboard

- src/components/Dropdown/Dropdown.tsx
We are fixing display of underscore for text in dopdown list.
**BEFORE**
**AFTER**
> fix display when text contain underscore

- src/components/Clipboard/Clipboard.tsx
[Screencast from 04-07-2023 17:50:18.webm](https://github.com/massalabs/ui-kit/assets/90157528/21fccc7e-02fd-4933-917f-c7d037ccc8aa)
BTW : you don't see the mouse on video but it is here ^^
By default it is true. We don't need to modify the code in our existing code base to make the feature functional. 
Possible to disable hover using the following param : 
``` 
toggleHover={false}
```
> Add hover to clipboard

- src/components/Dropdown/Dropdown.tsx
we add a button type to the drop down, because there is a bug in the bridge interface, where if we hit enter on the transfer form it opens the dropdown
> add button type to dropdown

- src/components/Plugin/Plugin.stories.tsx
- src/components/Plugin/Plugin.test.tsx
- src/components/Plugin/Plugin.tsx
[Screencast from 09-08-2023 14:47:02.webm](https://github.com/massalabs/ui-kit/assets/83134981/182d9070-139b-435c-bfe2-70918645633b)
> add plugin store not compatible

- src/components/Dropdown/Dropdown.tsx
- src/util/useClickOutside.ts
When users leave/click out of the dropdown it remains open until a new click on it. 
This MR fixes that!
We are now able to click anywhere to have it closed.
> Add auto close dropdown when leave component

- src/components/Card/Card.stories.tsx
- src/components/Card/Card.test.tsx
- src/components/Card/Card.tsx
We are adding a reusable card component
> Add card component

- src/components/DollarValue/DollarValue.tsx
- src/components/Token/Token.tsx
- src/lib/ConnectMassaWallets/components/MASBalance.tsx
- src/lib/util/handlePercent.test.ts
- src/lib/util/handlePercent.ts
- src/lib/util/parseAmount.stories.tsx
- src/lib/util/parseAmount.test.ts
- src/lib/util/parseAmount.ts
- removed `formatFTAmount`, use `formatAmount` instead
- renamed `amountFormattedFull` into `full`
- renamed `amountFormattedPreview` into `preview`
- removed `formatAmountToDisplay`, use `parseAmount` and `formatAmount`
- add story for format amount
- `formatAmount` preview has now at least 2 significant digits instead of 1
- `removeTrailingZeros` is not exported anymore
> refactor format amount
