massalabs/ui-kit

- presets/massa-station-preset.js
We missed a pre-name in warning color. This MR fixed that!
> fix warning color

- src/components/Input/Input.stories.tsx
- src/components/Input/Input.test.tsx
- src/components/Input/Input.tsx
- src/components/Input/index.ts
We are introducing the `<Input>` component.
> add `<Input>` component

- src/components/Password/Password.stories.tsx
- src/components/Password/Password.tsx
We are updating `<Password>` component to rely on global class instead of local.
> update password to apply global style

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
- src/components/Button/index.ts
- src/global.css
We are adding the primary button
> add primary button

- presets/massa-station-preset.js
We are fixing some mixed colors.
> fix colors

- src/components/index.ts
We are re-indexing exports for each component.
> change index export

- src/components/Button/Button.tsx
We are updating the IconContext import.
> update path for IconContext import

- src/components/Stepper/Stepper.tsx
We need to change to width of last step so it can be centered in parent div
> changed last step to have w-fit

- .storybook/preview.tsx
We are adding a **light** mode on storybook preview
> add ligth to preview

- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.test.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tabs/index.ts
- src/components/index.ts
- src/global.css
> add tabs component

- .storybook/preview.tsx
We named **light** mode wrongly. This MR fix that.
> fix color name

- src/components/Password/Password.tsx
We don't need onChange on password.
> remove onChange from password

- src/components/PopupModal/PopupModal.stories.tsx
- src/components/PopupModal/PopupModal.test.tsx
- src/components/PopupModal/PopupModal.tsx
- src/components/PopupModal/index.ts
We are adding a `<PopUpModal>` modal component.
> add popup-modal

- vite.config.ts
This MR aims fix the missing react import when using ui-kit
> fix react vite

- src/components/DragDrop/DragDrop.stories.tsx
- src/components/DragDrop/DragDrop.test.tsx
- src/components/DragDrop/DragDrop.tsx
- src/components/DragDrop/index.ts
We are adding `<DragDrop>` component
> add drag & drop

- src/components/DragDrop/DragDrop.stories.tsx
- src/components/DragDrop/DragDrop.test.tsx
- src/components/DragDrop/DragDrop.tsx
We are improving the drag & drop for allowed X non allowed files!
> drag and drop improve

- src/global.css
We are adding placeholder check in order to deal with uncontrolled components.
> add placeholder check

- src/components/Icons/Svg/Massa/MassaToken.tsx
- src/components/Icons/Svg/Massa/MassaWallet.tsx
- src/components/Icons/Svg/Massa/index.ts
- src/components/Icons/Svg/SvgIcon.stories.tsx
We are adding massa wallet logo
> add massa wallet logo

- src/components/Dropdown/Dropdown.tsx
We are fixing the dropdown color
> fix dropdown color

- src/components/Tabs/Tabs.tsx
- src/global.css
We have some font delay when clicking and activing a tab. This MR fix that.
> fix tab delay

- src/components/Icons/Svg/Massa/MassaLogo.tsx
- src/components/Icons/Svg/Massa/MassaToken.tsx
- src/components/Icons/Svg/Massa/MassaWallet.tsx
We are fixing some issues with svgs
> fix svg overrides

- src/global.css
We are fixing tailwind styles.
> fix tailwind styles

- .storybook/preview.tsx
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
- src/global.css
We are rolling back class on buttons
> rollback button class

- src/components/SideMenu/SideMenu.tsx
> fix menu color

- src/global.css
We had some issues concerning css overrides. This MR fix that.
> fix globals and tailwind overrides

- src/components/Password/Password.stories.tsx
add default values in storybook pass fields
> add default values in password storybook

- src/components/Icons/Svg/index.ts
- src/components/Icons/index.ts
- src/components/index.ts
> add path to svg

- src/components/Toggle/Toggle.stories.tsx
- src/components/Toggle/Toggle.test.tsx
- src/components/Toggle/Toggle.tsx
- src/components/Toggle/index.ts
- src/components/index.ts
We are adding a `<Toggle>` component
> add toggle

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
> add coins button

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
We are adding in `Dropdown` component the param to have one item selected as default
> add default select for dropdown options

- src/components/Balance/Balance.stories.tsx
- src/components/Balance/Balance.test.tsx
- src/components/Balance/Balance.tsx
- src/components/Balance/index.ts
- src/components/index.ts
We are adding the `<Balance>` component
> add balance component

- src/components/Button/Button.tsx
We are fixing some margin on buttons
> fix button margin

- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
We are updating the `<Input>` component API to accept icons
> update input fields API

- src/util/useLocalStorage.ts
We are adding useLocalStorage to use in some components
> add useLocalStorage

- src/components/DragDrop/DragDrop.stories.tsx
- src/components/DragDrop/DragDrop.tsx
We need a file callback when load/drop a file. This MR fix that
> add file return

- src/components/Balance/Balance.tsx
We are adding a customClass under balance to be able to override class when needed
> add customClass under balance

- src/components/Icons/Svg/Massa/MassaToken.tsx
We are adding a customClass under massa token to be able to override class when needed
> add custom class unde Massa Token

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/global.css
We are adding a customClass under buttons to be able to override class when needed
> add customClass under button components

- src/components/AccountSelector/AccountSelector.stories.tsx
- src/components/AccountSelector/AccountSelector.tsx
We are updating the account selector API
> update account update API

- src/components/Button/Button.tsx
We miss the interface on button classes. This MR fix that!
> add interface for button classes

- presets/massa-station-preset.js
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Colors/Color.tsx
- src/global.css
We are adding danger variant in ui-kit.
> add danger variant

- src/components/SideMenu/SideMenu.stories.tsx
- src/components/SideMenu/SideMenu.tsx
We have som padding on menu we missed. This MR fixes that!
> fix menu width

- src/components/index.ts
We are adding export for `Identicon` component in `index.ts`.
> add export for Identicon component

- src/components/Selector/Selector.tsx
> moving icon to the right

- src/components/Transaction/Transaction.stories.tsx
- src/components/Transaction/Transaction.test.tsx
- src/components/Transaction/Transaction.tsx
- src/components/Transaction/index.ts
- src/components/index.ts
similare to this component called "Selector":
> add transaction component

- presets/massa-station-preset.js
We are adding new class on preset.
> add new class on preset

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/global.css
We are adding new buttons versions.
> add button versions

- src/components/Button/Button.tsx
- src/global.css
> fix button colors

- src/components/Icons/Svg/Massa/MassaWallet.tsx
- src/components/Plugin/Plugin.stories.tsx
- src/components/Plugin/Plugin.test.tsx
- src/components/Plugin/Plugin.tsx
- src/components/Plugin/index.ts
- src/components/index.ts
we are adding `<Plugin>` card component
> add plugin

- src/components/Dropdown/Dropdown.tsx
> We try to fix wallet error on refresh... see desc

- src/components/Description/Description.stories.tsx
- src/components/Description/Description.test.tsx
- src/components/Description/Description.tsx
- src/components/Description/index.ts
- src/components/index.ts
> add description component

- src/components/PopupModal/PopupModal.tsx
> add custom class

- src/components/PopupModal/PopupModal.tsx
> fix modal padding

- src/components/RadioButton/RadioButton.tsx
> remove radio padding

- src/components/SidePanel/SidePanel.stories.tsx
- src/components/SidePanel/SidePanel.test.tsx
- src/components/SidePanel/SidePanel.tsx
- src/components/SidePanel/index.ts
> add sidePanel component

- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/Pagination.test.tsx
- src/components/Pagination/Pagination.tsx
- src/components/Pagination/index.ts
- src/components/index.ts
> add pagination component

- src/components/IconNavigator/IconNavigator.stories.tsx
- src/components/IconNavigator/IconNavigator.test.tsx
- src/components/IconNavigator/IconNavigator.tsx
- src/components/IconNavigator/index.ts
- src/components/SidePanel/SidePanel.tsx
- src/components/index.ts
We are adding a new component entitle : `IconNavigator`.
> add IconNavigator component

- src/components/Navigator/Navigator.stories.tsx
- src/components/Navigator/Navigator.test.tsx
- src/components/Navigator/Navigator.tsx
We are refactoring component `Navigator`.
> refactor Navigator component

- src/components/LayoutStation/LayoutStation.stories.tsx
- src/components/LayoutStation/LayoutStation.test.tsx
- src/components/LayoutStation/LayoutStation.tsx
- src/components/LayoutStation/index.ts
- src/components/index.ts
We are adding the Station layout
> add station layout

- src/components/LayoutStation/LayoutStation.tsx
> improve conditional

- src/components/Balance/Balance.stories.tsx
- src/components/Balance/Balance.tsx
We are removing padding and background in `Balance` component.
> remove padding and background on balance

- src/components/Description/Description.tsx
> fix description component

- src/components/SidePanel/SidePanel.tsx
rotate the side panel icon by 90°
> Rotate 90deg side panel icon

- src/assets/plugins/wallet/walletActive.svg
- src/assets/plugins/wallet/walletInactive.svg
- src/components/PluginWallet/PluginWallet.stories.tsx
- src/components/PluginWallet/PluginWallet.test.tsx
- src/components/PluginWallet/PluginWallet.tsx
- src/components/PluginWallet/index.ts
> add PluginWallet component

- package-lock.json
- package.json
- src/components/Currency/Currency.stories.tsx
- src/components/Currency/Currency.test.tsx
- src/components/Currency/Currency.tsx
- src/components/Currency/index.ts
- src/components/index.ts
> Add currency

- src/components/PopupModal/PopupModal.tsx
> add z-index in modal

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
we are fixing the dropdown truncate content
> fix dropdown truncate

- src/components/Dropdown/Dropdown.tsx
> fix dropdown size

- src/components/SidePanel/SidePanel.tsx
We change the color of the icon in the side menu to neutral
> Add Correct Color to Side Panel 

- src/components/Plugin/Plugin.stories.tsx
- src/components/Plugin/Plugin.tsx
> Add Icon to Plugin Variant

- src/components/ThemeMode/ThemeMode.tsx
We are changing value of theme from`dark` to `theme-dark`.
> change theme value in storage

- src/components/Input/Input.tsx
- src/components/Password/Password.tsx
- src/components/TextArea/TextArea.stories.tsx
- src/components/TextArea/TextArea.test.tsx
- src/components/TextArea/TextArea.tsx
- src/components/TextArea/index.ts
- src/components/index.ts
- src/global.css
We are adding new component `TextArea`.
> add TextArea component

- src/components/Currency/Currency.tsx
- src/components/Password/Password.tsx
- src/components/index.ts
We are adding some missing export values.
> fix export

- src/components/Vote/Vote.stories.tsx
- src/components/Vote/Vote.test.tsx
- src/components/Vote/Vote.tsx
- src/components/Vote/index.ts
- src/components/index.ts
We are adding compoent `Vote`.
> add vote component

- src/components/Spinner/Spinner.stories.tsx
- src/components/Spinner/Spinner.test.tsx
- src/components/Spinner/Spinner.tsx
- src/components/Spinner/index.ts
We are adding `Spinner` component.
> add spinner component

- src/components/Spinner/Spinner.stories.tsx
- src/components/Spinner/Spinner.tsx
We are adding variant `button` for `Spinner`.
> add variant button for spinner

- src/components/Spinner/Spinner.stories.tsx
- src/components/Spinner/Spinner.tsx
Spinner should follows button disabled. This MR fix that!
> spinner color

- src/components/Dropdown/Dropdown.tsx
We are adding `z-index` property for the modal.
> add z-index on dropdown

- src/components/PopupModal/PopupModal.tsx
We are adding `z-index` for `PopUpModal`.
> add z-index on modal

- src/components/DashboardStation/DashboardStation.stories.tsx
- src/components/PluginWallet/PluginWallet.stories.tsx
- src/components/PluginWallet/PluginWallet.test.tsx
- src/components/PluginWallet/PluginWallet.tsx
moves the logic of the Spinner/isLoading into the component PluginWallet
> rework pluginWallet

- src/components/PopupModal/PopupModal.tsx
- src/components/SidePanel/SidePanel.tsx
We are adding `z-index` fro `SidePanel`.
> add z-index for side panel

- src/components/Clipboard/Clipboard.tsx
https://github.com/massalabs/station-massa-wallet/issues/426 see here for more information
> Remove the underline in clipboard

- src/components/Input/Input.tsx
We are adding `type="button"` for the button in the icon `Input` component.
> add type button for button in input with icon

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
So far, the dropdown component had no ready only mode. This MR fixes that
> add readOnly option to dropdown

- src/components/Tag/Tag.stories.tsx
- src/components/Tag/Tag.test.tsx
- src/components/Tag/Tag.tsx
We are adding new type `default`.
> add new type default

- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.test.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/index.ts
> Add tooltip

- src/components/Icons/Svg/Massa/Mrc20.tsx
- src/components/Icons/Svg/Massa/Mrc721.tsx
- src/components/Token/Token.stories.tsx
- src/components/Token/Token.tsx
we add disable because the user cannot delete massa token
> Small token improvements

- .eslintignore
- jest.config.cjs
- jest.setup.ts
- package-lock.json
- package.json
- src/components/Icons/Svg/Massa/Mrc20.tsx
- src/components/Icons/Svg/Massa/Mrc721.tsx
- src/components/Token/Token.stories.tsx
- src/components/Token/Token.test.tsx
- src/components/Token/Token.tsx
> Rework token component

- src/components/Icons/Svg/Massa/BridgeLogo.tsx
We are removing bg color on the `BridgeLogo` Icon.
> ui-kit: remove bg color

- src/components/FAQ/FAQ.tsx
we add optional state param to be able to toggle on and off with a user click
> Little rework of the FAQ component

- src/components/Plugin/Plugin.stories.tsx
- src/components/Plugin/Plugin.tsx
> Add Verison to Store Plugin

- src/components/Plugin/Plugin.stories.tsx
- src/components/Plugin/Plugin.tsx
> Add plugin version to plugin action

- src/components/Balance/Balance.stories.tsx
- src/components/Balance/Balance.tsx
We are adding a middle size option for `<Balance>` component
> add md size for balance tag

- .husky/pre-push
- package.json
- src/components/Button/Button.stories.tsx
- src/components/PluginWallet/PluginWallet.tsx
- src/components/Spinner/Spinner.stories.tsx
- src/components/Spinner/Spinner.tsx
Fix the spinner color by simplifying, taking the spinner created first in the bridge
> Add sized spinner

- src/components/RedirectTile/RedirectTile.stories.tsx
- src/components/RedirectTile/RedirectTile.test.tsx
- src/components/RedirectTile/RedirectTile.tsx
- src/components/RedirectTile/index.ts
- src/components/index.ts
- src/util/utils.ts
We are adding new tile component that is going to be used in the context of this mission :
https://www.notion.so/massa-innoteam/Revamp-Home-Page-MS-8cc4bb1e30a74359913e460e8a57acc3
It will be used when we need to link and external massa project
> Add new redirect tile component

- src/components/Token/Token.stories.tsx
- src/components/Token/Token.tsx
> add dollar value in Token

- src/components/Icons/Svg/FT/FTIcons.stories.tsx
> add FT story

- src/components/MNS/Mns.stories.tsx
- src/components/MNS/Mns.test.tsx
- src/components/MNS/Mns.tsx
- src/components/MNS/index.ts
- src/components/index.ts
We are adding the Mns component which allows us to correctly display a massa mns
> Add Mns Component

- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
We are fixing the input success message in order for the success param to work
> fix input success message

- src/components/Toast/Toast.stories.tsx
- src/components/Toast/Toast.tsx
we are fixing toast text color for better readability
> Fix toast colors

- src/components/Token/Token.tsx
- src/components/Tooltip/Tooltip.tsx
> Remove tooltip padding
